name: e_learning
description: "E-learning App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
# Localization
  flutter_localizations:
    sdk: flutter
# Code generator.
  build_runner:
# Connectivity
  connectivity_plus:
# Splashing
  flutter_native_splash:
# State management.
  flutter_bloc:
# Code generation for immutable classes (cubit & retrofit).
  freezed:
  freezed_annotation:
# Dependency injection.
  get_it:
# Classes and helper functions that support JSON code generation.
  json_annotation:
  json_serializable:
# Networking
  dio:
  retrofit:
  retrofit_generator:
  pretty_dio_logger:
# UI
  flutter_screenutil:
  cached_network_image:
  flutter_svg:
  lottie:
  smooth_page_indicator:
# Data Storage
  shared_preferences:
# Device preview
  device_preview:

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
    - assets/icons/
    - assets/images/
    - assets/lotties/
    - assets/translations/



  fonts:
    - family: lexend
      fonts:
        - asset: assets/fonts/lexend/lexend-Black.ttf
        - asset: assets/fonts/lexend/lexend-Bold.ttf
        - asset: assets/fonts/lexend/lexend-ExtraBold.ttf
        - asset: assets/fonts/lexend/lexend-ExtraLight.ttf
        - asset: assets/fonts/lexend/lexend-Light.ttf
        - asset: assets/fonts/lexend/lexend-Medium.ttf
        - asset: assets/fonts/lexend/lexend-Regular.ttf
        - asset: assets/fonts/lexend/lexend-SemiBold.ttf
        - asset: assets/fonts/lexend/lexend-Thin.ttf
